name: sketch-primitives
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - matplotlib=3.5.2
  - numpy=1.23.1
  - pillow=9.2.0
  - pip=22.1.2
  - python=3.10.5
  - pytorch=1.12.0
  - tar=1.34
  - tensorboard=2.9.1
  - torchvision=0.13.0
  - tqdm=4.64.0
  - wget=1.20.3
